# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Text.destroy_all

Text.create(content: 'Ea ipsa quae ab illo inventore veritatis. Voluptatibus provident non tempore cupiditate ut obcaecati. Dolor iste natus error sit reprobandi et laudandi. Nemo enim ipsam voluptatem aspernatur aut odit aut fugit. Voluptas. Voluptas. Voluptates atque molestias, qui tenetur, similique sunt in culpa qui officia deserunt mollitia animi. Sed contra, accusamus et iusto odio dignissimos ducimus qui voluptates voluptatum. Voluptate, qui officia deserunt impedit laborum et dolorum. Tenetur id sapiente architecto sapiente assumenda est. Et omnis voluptas assumenda est. Humanae felicitatis: dolor, voluptas. Voluptate velit esse quam nihil pariatur, vel illum qui dolorem eum fugiat quo voluptas sit aspernatur.')
Text.create(content: 'Hic error sit repudiandae eaque laudantium dolorem. Ea ipsa quae ab illo inventore veritatis. Doloribus voluptates doloribus praesentium. Voluptate, voluptas, voluptatibus et molestias tenetur consequatur. Par autem culpae est eorum qui se ex infirmitate voluntatis deficiunt. Sed contra, cum indignatione iustorum, et odiosa est nobis voluptas. Voluptates, voluptates, qui officia deserunt impedit laborum et dolorum. Fugiat architecto. Semper in sapiente itaque suscipit, omnis voluptas assumenda est, omnis voluptas assumenda est. Doloremque voluptates beatae vitae dicta sunt. Voluptatem velit esse quam laborum voluptas sit aspernatur aut odit aut fugit. Par autem culpa est eorum qui officio suo deficiunt. Dolor.')
Text.create(content: 'Voluptate, voluptas, voluptatibus. Consequatur atque molestias assumenda est, eos qui officia deserunt mollitia animi. Sed contra, cum indignatione iustorum, et odiosa est nobis voluptas. Voluptates, voluptates, qui officia deserunt impedit laborum et dolorum. Fugiat architecto. Semper in sapiente suscipit, assumenda est, omnis voluptas assumenda est. Voluptatem quia voluptas sit aspernatur aut odit aut fugit qui dolorem ipsum quia voluptas sit aspernatur aut odit aut fugit. Iste natus error sit repudiandae dolor. Illo ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit pariatur dolor.')
Text.create(content: 'Voluptas asperiores et molestias id tenetur mollitia velit. Architecto. Quod idem est ac detrectatione laborum officiorumque doloribus. In libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit, assumenda est. Facere quod placeat facere possimus: dolor cum iusto odio et odio sunt. Facere, totam rem aperiam, eaque nostra quis nostrum exercitationem ullam corporis suscipit laboriosam, quam nihil molestiae consequatur. Dolor. Voluptas. Rerum humanarum felicitas. Haec sunt perfecte simplices et faciles ad distinguendum. Voluptatibus voluptatibus maiores alias consequatur. Ullo iure reprehenderit qui officia deserunt. Dolor. Voluptas cum nihil impedit nostrum esse. Repudiandae perspiciatis harum rerum consequatur voluptatem.')
Text.create(content: 'Sic decepta ac turpitudine voluptatum. Sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Facere, tibi dabo rationem integram. Voluptates sint provident voluptatem et molestiae non. Earum inventore veritatis et quasi culpa est eos qui deserunt. Dolor, iste natus error sit voluptatem accusantium laudantium. Electio soluta momento. Accusamus iusto dolore et molestiae non voluptatem. Sed ut perspiciatis unde omnis voluptate velit esse quam nihil pariatur. Quis nostrum exercitationem ullam corporis suscipit laboriosam? Voluptas beatae vitae. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates et iure. Causae sunt perfecte simplices et faciles ad distinguendum.')
Text.create(content: 'Facere, ai dabo, totam rem aperiam eaque dolor. Hose quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Par autem est eorum culpa, qui in officio suo sunt, et dolores. Dolore, cupiditate, architecto voluptatem non provident. Expedita libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus. Iste natus error sit voluptatem repudiandae. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates. Cum dolore iusto odio ducimus qui. Illo non provident voluptatem quia voluptas sit aspernatur aut. Voluptatibus, qui asperiores repellat, recusandae laborum sunt atque harum quidem rerum facilis est et expedita distinctio.')