# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Text.create(content: 'Voluptas. voluptas, architecto. Facere, ai dabo, totam rem aperiam eaque dolor. Hose quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Par autem est eorum culpa, qui in officio suo sunt, et dolores. Dolore, cupiditate, architecto voluptatem non provident. Expedita libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus. Iste natus error sit voluptatem repudiandae. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit. Cum dolore iusto odio ducimus qui. Illo non provident voluptatem quia voluptas sit aspernatur aut. Voluptatibus, qui asperiores repellat, recusandae laborum sunt atque harum quidem rerum facilis est et expedita distinctio. Voluptas, repellendus, possimus facere quod maxime possimus quasi. Omnis voluptas. Repudiandae perspiciatis harum rerum consequatur voluptatem.')
Text.create(content: 'Ea ipsa quae ab illo inventore veritatis. Voluptatibus provident non tempore cupiditate ut obcaecati. Dolor iste natus error sit reprobandi et laudandi. Nemo enim ipsam voluptatem aspernatur aut odit aut fugit. Voluptas. Voluptas. Voluptates atque molestias, qui tenetur, similique sunt in culpa qui officia deserunt mollitia animi. Sed contra, accusamus et iusto odio dignissimos ducimus qui voluptates voluptatum. Voluptate, qui officia deserunt impedit laborum et dolorum. Tenetur id sapiente architecto sapiente assumenda est. Et omnis voluptas assumenda est. Humanae felicitatis: dolor, voluptas. Voluptate velit esse quam nihil pariatur, vel illum qui dolorem eum fugiat quo voluptas sit aspernatur.')
Text.create(content: 'Hic error sit repudiandae eaque laudantium dolorem. Ea ipsa quae ab illo inventore veritatis. Doloribus voluptates doloribus praesentium. Voluptate, voluptas, voluptatibus et molestias tenetur consequatur. Par autem culpae est eorum qui se ex infirmitate voluntatis deficiunt. Sed contra, cum indignatione iustorum, et odiosa est nobis voluptas. Voluptates, voluptates, qui officia deserunt impedit laborum et dolorum. Fugiat architecto. Semper in sapiente itaque suscipit, omnis voluptas assumenda est, omnis voluptas assumenda est. Doloremque voluptates beatae vitae dicta sunt. Voluptatem velit esse quam laborum voluptas sit aspernatur aut odit aut fugit.')